/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
<<<<<<< HEAD
import { Route as TestRouteImport } from './routes/test'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
=======
import { Route as StyleGuideRouteImport } from './routes/style-guide'
import { Route as IndexRouteImport } from './routes/index'

const StyleGuideRoute = StyleGuideRouteImport.update({
  id: '/style-guide',
  path: '/style-guide',
>>>>>>> 3577596d2cf4bad026b02ce9526cfc12116701f5
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
=======
  '/style-guide': typeof StyleGuideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/style-guide': typeof StyleGuideRoute
>>>>>>> 3577596d2cf4bad026b02ce9526cfc12116701f5
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/test': typeof TestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/register' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/register' | '/test'
  id: '__root__' | '/' | '/login' | '/register' | '/test'
=======
  '/style-guide': typeof StyleGuideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/style-guide'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/style-guide'
  id: '__root__' | '/' | '/style-guide'
>>>>>>> 3577596d2cf4bad026b02ce9526cfc12116701f5
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TestRoute: typeof TestRoute
=======
  StyleGuideRoute: typeof StyleGuideRoute
>>>>>>> 3577596d2cf4bad026b02ce9526cfc12116701f5
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
<<<<<<< HEAD
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
=======
    '/style-guide': {
      id: '/style-guide'
      path: '/style-guide'
      fullPath: '/style-guide'
      preLoaderRoute: typeof StyleGuideRouteImport
>>>>>>> 3577596d2cf4bad026b02ce9526cfc12116701f5
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TestRoute: TestRoute,
=======
  StyleGuideRoute: StyleGuideRoute,
>>>>>>> 3577596d2cf4bad026b02ce9526cfc12116701f5
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
